# config/__init__.py
# Makes config directory a Python package

from .theme import THEME
from .file_config import (
    ASSETS_DIR, OUTPUT_DIR, SUPPORTED_IMAGE_FORMATS, SUPPORTED_PDF_FORMATS,
    MAX_FILE_SIZE, MAX_IMAGE_SIZE, ERROR_MESSAGES as FILE_ERROR_MESSAGES
)
from .pdf_config import (
    DEFAULT_DPI, COMPRESSION_LEVELS, DEFAULT_COMPRESSION,
    ERROR_MESSAGES as PDF_ERROR_MESSAGES
)
from .ocr_config import TESSERACT_CONFIG, OCR_LANGUAGES, ERROR_MESSAGES as OCR_ERROR_MESSAGES
from .app_config import APP_NAME, APP_VERSION, APP_AUTHOR, ANDROID_PERMISSIONS, BUILD_SETTINGS